### ISSUE TITLE
No proposed structure auto-gen?

### ISSUE THREAD

**Issue by woodsoul507** [kauemurakami/getx_snippets_extension#15]
Hello, I had the idea that this extension comes with a way to auto-gen folders as the proposed structure but cant find the way to do it yet. I am just doing it manually by now.

Thanks the great work on this extension!

**Comment by kauemurakami** [comment]
Hello, all here are snippets and Wrappers, to place your widgets inside an obx with Alt + o for example or using control +. and selected wrap in ObX / GetBuilder / GetWidget, but for that there is https://pub.dev/packages/get_cli, my proposed structure is out of date at the moment, but you can use other ones, or continue doing it, it is not quick: 3 hsuahusa thanks for support, enjoy.
