### ISSUE TITLE
Wrap feature issue

### ISSUE THREAD

**Issue by Maatteogekko** [kauemurakami/getx_snippets_extension#16]
Maybe I'm doing something wrong, but the wrap options related to getx are not showing no matter on what widget I try it on.
I am using vscode 1.55.2, getx snippets 4.0.0 and get 4.1.4. 
![Screenshot_20210506_173936](https://user-images.githubusercontent.com/54111322/117326915-66e9f900-ae92-11eb-889d-0a3cb9634e13.png)

**Comment by kauemurakami** [comment]
Test new version, avaible now

**Comment by Maatteogekko** [comment]
It works! But I think it wasn't working because the folder open inside vscode wasn't the root of the flutter application.
Nice response time btw!
