### ISSUE TITLE
how can i use this plugin in my AndroidStudio

### ISSUE THREAD

**Issue by dabinDev** [kauemurakami/getx_snippets_extension#18]
how can i use this plugin in my AndroidStudio ? i only find this plugin in vscode market

**Comment by kauemurakami** [comment]
Hello, for now I only keep pro vscode, but if I'm not mistaken it also has for inteliJ and AS, look in the plugin, otherwise it only exists for inteliJ and vs code.
I still don't think about creating the AS version for him
