### ISSUE TITLE
deprecated widgets

### ISSUE THREAD

**Issue by BikashBaishnab** [kauemurakami/getx_snippets_extension#20]
Its still showing deprecated values, please update it.

**Comment by kauemurakami** [comment]
which in specify?

**Comment by kauemurakami** [comment]
I will do it today!! sorry for the sloppiness !!

**Comment by kauemurakami** [comment]
I just fixed it! The update has already been sent! 
If you find something you missed, be sure to open an issue again! 
Thanks for helping to maintain the package!
