### ISSUE TITLE
Please support null safety (Flutter 2+)

### ISSUE THREAD

**Issue by MagnusJohansson** [kauemurakami/getx_snippets_extension#21]
When trying to use some snippets, such as the getform, the generated code is not null-safety compliant:
![image](https://user-images.githubusercontent.com/674909/128249224-a8d77391-0a2f-4513-8905-0defa620f4c9.png)

Also, it would be nice if the generated code is linted (with https://pub.dev/packages/lint for example).

**Comment by kauemurakami** [comment]
I will do it today!!

**Comment by MagnusJohansson** [comment]
By the way, this snippet shouldn't create the FormState key inside the build method, re-creating it at every build.

**Comment by kauemurakami** [comment]
Yes, this was one of the snippets I left behind, haha ​​but I just updated it, today I'm finishing everyone's update and I'll have a new version available!

**Comment by kauemurakami** [comment]
`import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:sacrafood/app/modules/login/controller.dart';

class CustomForm extends Container {
  final GlobalKey<FormState> _formKey = GlobalKey<FormState>();
  final controller = Get.find<LoginController>();
  @override
  Widget build(BuildContext context) {
    return Form(
        key: key,
        child: Column(
          children: <Widget>[
            TextFormField(
              keyboardType: TextInputType.emailAddress,
              decoration: InputDecoration(labelText: 'Email'),
              enableSuggestions: true,
              maxLength: 32,
              style: TextStyle(fontSize: 20),
              onSaved: (v) => this.controller.onSavedEmail(v),
              onChanged: (v) => this.controller.onChangedEmail(v),
              validator: (v) => this.controller.onValidateEmail(v),
            ),
            TextFormField(
              keyboardType: TextInputType.text,
              decoration: InputDecoration(labelText: 'Senha'),
              enableSuggestions: true,
              obscureText: true,
              maxLength: 20,
              style: TextStyle(fontSize: 20),
              onSaved: (v) => this.controller.onSavedPassword(v),
              onChanged: (v) => this.controller.onChangedPassword(v),
              validator: (v) => this.controller.onValidatePassword(v),
            ),
            MaterialButton(
              onPressed: () async {
                final FormState form = this._formKey.currentState!;
                if (form.validate()) {
                  form.save();
                  await this.controller.login();
                }
              },
              child: Text('OK'),
            )
          ],
        ));
  }
}
`
