### ISSUE TITLE
Cannot use getx_snippets

### ISSUE THREAD

**Issue by skylastn** [kauemurakami/getx_snippets_extension#29]
i've installed getx_snippets in my vscode, but got warning & didn't work well, 

Warning message : You can now use the lamp by clicking on the name of the widget. The shortcut keys have been disabled.

**Comment by kauemurakami** [comment]
here everything is ok, even though it is not possible to update yet.
All wrappers were contributions, I need to see the code well, I'm still out of time :/
sorry
