### ISSUE TITLE
Cursor Placement issue.

### ISSUE THREAD

**Issue by manojeeva** [kauemurakami/getx_snippets_extension#7]
getpage snippet cursor not going to YourController.
Also, We got a controller using binding. We don't need GetX<T> Inside the widget, right? (Maybe that's an option we can use other controllers).
Maybe we can create another snippet with getpagewithcontroller.

![getpage](https://user-images.githubusercontent.com/46526800/92984756-3ea82700-f4ca-11ea-8fd7-fd4b0fc5cbee.PNG)

getbinding prints wrong snippet Some syntax issue

![getbinding](https://user-images.githubusercontent.com/46526800/92984856-1f5dc980-f4cb-11ea-9731-c07b94a6e17f.PNG)

Running in Windows 7. Extension using the latest version. VS Code Latest Version.

**Comment by kauemurakami** [comment]
Thanks for your information, sorry for the delay, I will correct it as soon as possible, probably tomorrow.
Somehow I was not notified of your problem.
Thank you for contributing.

**Comment by kauemurakami** [comment]
I just uploaded version 3.1.4 to the marketplace, now it's fixed !!
